/*using Grasshopper.Kernel.Types;
using Rhino.Geometry;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TSD_API_ver101._081_Utils_BendingShape
{
    public class BendingShape_GH
    {

        public static List<Curve> BendingShapeLine(int Code, double A, double B, double C, double D, double E, double F, double r, double d)
        {
            



        }

        public static List<Curve> Bending00(double A, double B, double C, double D, double E, double F, double r, double d)
        {
            List<Curve> result = new List<Curve>();

            Point3d point_0 = new Point3d(0,0,0);
            Point3d point_1 = new Point3d(A,0,0);
            Curve output_curve_1 = Curve.CreateControlPointCurve(new List<Point3d> {point_0,point_1}, 1);
            result.Add(output_curve_1);




            return result;

        }



    }
}
*/